eureka:
    client:
        serviceUrl:
            defaultZone: http://minimintserverregistryserver.azurewebsites.net:80/eureka/
        registerWithEureka: true
        fetchRegistry: true
    instance:
        hostname: ${HOSTNAME}
